# coding: utf-8

"""
    Kubernetes CRD Swagger

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class IoK8sNetworkingGatewayV1GRPCRouteSpecRulesInnerMatchesInnerMethod(BaseModel):
    """
    Method specifies a gRPC request service/method matcher. If this field is not specified, all services and methods will match.
    """ # noqa: E501
    method: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Value of the method to match against. If left empty or omitted, will match all services.  At least one of Service and Method MUST be a non-empty string.")
    service: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Value of the service to match against. If left empty or omitted, will match any service.  At least one of Service and Method MUST be a non-empty string.")
    type: Optional[StrictStr] = Field(default='Exact', description="Type specifies how to match against the service and/or method. Support: Core (Exact with service and method specified)  Support: Implementation-specific (Exact with method specified but no service specified)  Support: Implementation-specific (RegularExpression)")
    __properties: ClassVar[List[str]] = ["method", "service", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Exact', 'RegularExpression']):
            raise ValueError("must be one of enum values ('Exact', 'RegularExpression')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoK8sNetworkingGatewayV1GRPCRouteSpecRulesInnerMatchesInnerMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoK8sNetworkingGatewayV1GRPCRouteSpecRulesInnerMatchesInnerMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "method": obj.get("method"),
            "service": obj.get("service"),
            "type": obj.get("type") if obj.get("type") is not None else 'Exact'
        })
        return _obj


